export const learning = [
    {
        "url": "https://medium.com/cyberdefendersprogram/python-for-cyber-security-lesson-1-introduction-to-python-1976d817976",
        "title": "Python for Cybersecurity-Lesson 1: Introduction to Python",
        "desc": "Wondering why specific focus is being given to cybersecurity or why should you bother? Well, the answer is pretty simple. <h5 class='standout'> “You are only secure until you believe you are secure.”</h5>",
        "week": "03",
        "sort": "2022-05-11",
        "date": "24 July 2018",
        "accessed": "xxxxxx",
        "author": "Johnsy Vineela",
        "authlink": "https://medium.com/@johnsyvineela?source=post_page-----1976d817976--------------------------------",
        "imgcred": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "PpB92zhBD-XR-ZqH.jpg",
        "term": "Jupyter Notebook",
        "termdef": "The Jupyter Notebook is the original web application for creating and sharing computational documents. It offers a simple, streamlined, document-centric experience."
    },
    {
        "url": "https://tryhackme.com/room/netsecchallenge",
        "title": "Try Hack Me: Net Sec Challenge",
        "desc": "Practice the skills you have learned in the Network Security module.",
        "week": "04",
        "sort": "2022-05-12",
        "date": "12 May 2022",
        "accessed": "xxxxxx",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "netsecmodule.png",
        "term": "Nmap",
        "termdef": "<a href='https://nmap.org/'>(Network Mapper)</a> is a free and open source utility for network discovery and security auditing. Many systems and network administrators also find it useful for tasks such as network inventory, managing service upgrade schedules, and monitoring host or service uptime."
    }
    ,
    {
        "url": "https://www.bugcrowd.com/hackers/",
        "title": "LEARN, HACK, EARN",
        "desc": "Welcome to Bugcrowd, the Home for Hackers and Security Researchers <br>  <a href='https://bugcrowd.com/user/sign_up'>Sign up for bugcrowd</a>",
        "week": "04",
        "sort": "2022-05-11",
        "date": "11 May 2022",
        "accessed": "xxxx",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "James Wainscoat on Unsplash.com",
        "imgcred": "https://unsplash.com/@tumbao1949",
        "img": "james-wainscoat-GGewLGcQD-I-unsplash.jpg",
        "term": "Bug Bounty Hunter",
        "termdef": "Bug bounty hunters are highly-skilled hackers who detect security vulnerabilities and they are one of the most sought after professions in Japan today. The struggles to cope with rising threat of cyberattacks, along with huge costs that can incur to recuperate the losses are driving organisations to strengthen their  cyber security."
    }
    ,
    {
        "url": "https://azureforeducation.microsoft.com/devtools",
        "title": "xxxx",
        "desc": "Hey y'all! If any of you want a Microsoft Windows key, the school gives us two free keys. Click software from list on the left side, then search windows, and you should find download links. Click it and it opens a side panel where you can get the key from.",
        "week": "05",
        "sort": "2022-05-19",
        "date": "19 May 2022",
        "accessed": "19 May 2022",
        "author": "Shared by Riley",
        "authlink": "xxxx",
        "imgcred": "xxxx",
        "imgcredlink": "xxxx",
        "img": "Azure.png",
        "term": "Azure",
        "termdef": "The Azure cloud platform is more than 200 products and cloud services designed to help you bring new solutions to life—to solve today’s challenges and create the future. Build, run, and manage applications across multiple clouds, on-premises, and at the edge, with the tools and frameworks of your choice."
    }
    ,
    {
        "url": "https://tryhackme.com/room/xssgi",
        "title": "Cross-site Scripting (XSS)",
        "desc": "Learn how to detect and exploit XSS vulnerabilities, giving you control of other visitor's browsers.",
        "week": "06",
        "sort": "2022-05-26",
        "date": "26 May 2022",
        "accessed": "26 May 2022",
        "author": "Presented by Dax",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "2022-spring-06-ig-owasp-xss.png",
        "term": "XSS",
        "termdef": "Cross-Site Scripting (XSS) is a type of injection attack in which malicious scripts are injected into otherwise benign and trusted web pages. An attacker can exploit a vulnerability in an application to steal or modify legitimate data."
    }
    ,
    {
        "url": "https://www.base64decode.org/",
        "title": "Base64 Decoder",
        "desc": "Do you have to deal with Base64 format? Then this site is perfect for you! Use our super handy online tool to encode or decode your data.",
        "week": "06",
        "sort": "2022-05-26",
        "date": "26 May 2022",
        "accessed": "26 May 2022",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "https://www.base64-image.de/",
        "imgcred": "base64-image",
        "img": "base64.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://tryhackme.com/room/nmap01",
        "title": "TryHackMe | Nmap Live Host Discovery",
        "desc": "Learn how to use Nmap to discover live hosts using ARP scan, ICMP scan, and TCP/UDP ping scan.When we want to target a network, we want to find an efficient tool to help us handle repetitive tasks and answer the following questions: Which systems are up? What services are running on these systems?",
        "week": "05",
        "sort": "2022-05-09",
        "date": "09 May 2022",
        "accessed": "09 May 2022",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcred": "xxxx",
        "imgcredlink": "xxxx",
        "img": "a6b64823d42120e106cb7e89ceaa4817.png",
        "term": "ARP",
        "termdef": "Address Resolution Protocol is a communication protocol used for discovering the link layer address, such as a MAC address, associated with a given internet layer address, typically an IPv4 address."
    }
    ,
    {
        "url": "https://xsshunter.com/",
        "title": "What is XSS Hunter?",
        "desc": "XSS Hunter allows you to find all kinds of cross-site scripting vulnerabilities, including the often-missed blind XSS. The service works by hosting specialized XSS probes which, upon firing, scan the page and send information about the vulnerable page to the XSS Hunter service.",
        "week": "06",
        "sort": "2022-05-26",
        "date": "26 May 2022",
        "accessed": "26 May 2022",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "automatic_page_recon.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    // ,
    // {
    //     "url": "https://tryhackme.com/room/owaspjuiceshop",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "06",
    //     "sort": "2022-05-26",
    //     "date": "26 May 2022",
    //     "accessed": "26 May 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "https://tryhackme.com/room/burpsuitebasics",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-26",
    //     "date": "26 May 2022",
    //     "accessed": "11 May 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "https://tryhackme.com/room/burpsuiterepeater",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "11 May 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "https://tryhackme.com/room/introtonetworking",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "11 May 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "https://tryhackme.com/hacktivities",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "11 May 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    ,
    {
        "url": "https://tryhackme.com/path-action/beginner/join",
        "title": "Try Hack Me Complete Beginner Path",
        "desc": "This path will be looking at the following areas: Basic Linux - Get familiar with the linux command line, Web Application Security - Learn web application security concepts through the OWASP Top 10, Network Security - Using essential tools like NMAP to enumerate infrastructure, Scripting Challenges - Using Python and Bash to carry out different tasks, Privilege Escalation",
        "week": "xxxx",
        "sort": "2022-05-11",
        "date": "11 May 2022",
        "accessed": "xxxx",
        "author": "xxxx",
        "authlink": "https://tryhackme.com",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "deploy_access_hack_arrow.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    // ,
    // {
    //     "url": "https://tryhackme.com/room/pythonbasics",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "06",
    //     "sort": "2022-05-20",
    //     "date": "20 May 2022",
    //     "accessed": "20 May 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "https://tryhackme.com/room/pythonforcybersecurity",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "06",
    //     "sort": "2022-05-23",
    //     "date": "23 May 2022",
    //     "accessed": "23 May 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "https://www.phishingbox.com/phishing-test",
    //     "title": "PhishingBox - Phishing Test",
    //     "desc": "Take this test to see if you can identify what is a real email or a phishing email. This is not an easy test. If you can continuously make an ‘A’ on this test, then you can effectively identify Phishing scams. PhishingBox’s built-in security awareness training will help you educate your employees by properly testing them with Phishing Quizzes and educational online courses to help combat the ongoing phishing threat.",
    //     "week": "07",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "https://www.awseducate.com/student/s/",
    //     "title": "AWS Educate",
    //     "desc": "Your cloud journey starts here! No matter your goal, we’ve gathered the most useful content to build your cloud skills.",
    //     "week": "07",
    //     "sort": "2022-06-02",
    //     "date": "02 June 2022",
    //     "accessed": "02 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
];