export const learning = [
    {
        "url": "https://medium.com/cyberdefendersprogram/python-for-cyber-security-lesson-1-introduction-to-python-1976d817976",
        "title": "Python for Cybersecurity-Lesson 1: Introduction to Python",
        "desc": "Wondering why specific focus is being given to cybersecurity or why should you bother? Well, the answer is pretty simple. <h5 class='standout'> “You are only secure until you believe you are secure.”</h5>",
        "week": "03",
        "sort": "2022-05-11",
        "date": "24 July 2018",
        "accessed": "xxxxxx",
        "author": "Johnsy Vineela",
        "authlink": "https://medium.com/@johnsyvineela?source=post_page-----1976d817976--------------------------------",
        "imgcred": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "PpB92zhBD-XR-ZqH.jpg",
        "term": "xxxx",
        "termdef": "xxxx"
    },
    {
        "url": "https://tryhackme.com/room/netsecchallenge",
        "title": "Try Hack Me: Net Sec Challenge",
        "desc": "Practice the skills you have learned in the Network Security module.",
        "week": "04",
        "sort": "2022-05-12",
        "date": "12 May 2022",
        "accessed": "xxxxxx",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "netsecmodule.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://www.bugcrowd.com/hackers/",
        "title": "LEARN, HACK, EARN",
        "desc": "Welcome to Bugcrowd, the Home for Hackers and Security Researchers <br>  <a href='https://bugcrowd.com/user/sign_up'>Sign up for bugcrowd</a>",
        "week": "04",
        "sort": "2022-05-11",
        "date": "11 May 2022",
        "accessed": "xxxx",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "James Wainscoat on Unsplash.com",
        "imgcred": "https://unsplash.com/@tumbao1949",
        "img": "james-wainscoat-GGewLGcQD-I-unsplash.jpg",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://azureforeducation.microsoft.com/devtools",
        "title": "xxxx",
        "desc": "Hey y'all! If any of you want a Microsoft Windows key, the school gives us two free keys. Click software from list on the left side, then search windows, and you should find download links. Click it and it opens a side panel where you can get the key from.",
        "week": "05",
        "sort": "2022-05-19",
        "date": "19 May 2022",
        "accessed": "19 May 2022",
        "author": "Shared by Riley",
        "authlink": "xxxx",
        "imgcred": "xxxx",
        "imgcredlink": "xxxx",
        "img": "xxxx",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "05",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "05",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-05-11",
    //     "date": "11 May 2022",
    //     "accessed": "xxxx",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
];