export const learning = [
    {
        "url": "https://medium.com/cyberdefendersprogram/python-for-cyber-security-lesson-1-introduction-to-python-1976d817976",
        "title": "Python for Cybersecurity-Lesson 1: Introduction to Python",
        "desc": "Wondering why specific focus is being given to cybersecurity or why should you bother? Well, the answer is pretty simple. <h5 class='standout'> “You are only secure until you believe you are secure.”</h5>",
        "week": "03",
        "sort": "2022-05-11",
        "date": "24 July 2018",
        "accessed": "xxxxxx",
        "author": "Johnsy Vineela",
        "authlink": "https://medium.com/@johnsyvineela?source=post_page-----1976d817976--------------------------------",
        "imgcred": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "PpB92zhBD-XR-ZqH.jpg",
        "term": "Jupyter Notebook",
        "termdef": "The Jupyter Notebook is the original web application for creating and sharing computational documents. It offers a simple, streamlined, document-centric experience."
    },
    {
        "url": "https://tryhackme.com/room/netsecchallenge",
        "title": "Try Hack Me: Net Sec Challenge",
        "desc": "Practice the skills you have learned in the Network Security module.",
        "week": "04",
        "sort": "2022-05-12",
        "date": "12 May 2022",
        "accessed": "xxxxxx",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "netsecmodule.png",
        "term": "Nmap",
        "termdef": "<a href='https://nmap.org/'>(Network Mapper)</a> is a free and open source utility for network discovery and security auditing. Many systems and network administrators also find it useful for tasks such as network inventory, managing service upgrade schedules, and monitoring host or service uptime."
    }
    ,
    {
        "url": "https://www.bugcrowd.com/hackers/",
        "title": "LEARN, HACK, EARN",
        "desc": "Welcome to Bugcrowd, the Home for Hackers and Security Researchers <br>  <a href='https://bugcrowd.com/user/sign_up'>Sign up for bugcrowd</a>",
        "week": "04",
        "sort": "2022-05-11",
        "date": "11 May 2022",
        "accessed": "xxxx",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "James Wainscoat on Unsplash.com",
        "imgcred": "https://unsplash.com/@tumbao1949",
        "img": "james-wainscoat-GGewLGcQD-I-unsplash.jpg",
        "term": "Bug Bounty Hunter",
        "termdef": "Bug bounty hunters are highly-skilled hackers who detect security vulnerabilities and they are one of the most sought after professions in Japan today. The struggles to cope with rising threat of cyberattacks, along with huge costs that can incur to recuperate the losses are driving organisations to strengthen their  cyber security."
    }
    ,
    {
        "url": "https://azureforeducation.microsoft.com/devtools",
        "title": "xxxx",
        "desc": "Hey y'all! If any of you want a Microsoft Windows key, the school gives us two free keys. Click software from list on the left side, then search windows, and you should find download links. Click it and it opens a side panel where you can get the key from.",
        "week": "05",
        "sort": "2022-05-19",
        "date": "19 May 2022",
        "accessed": "19 May 2022",
        "author": "Shared by Riley",
        "authlink": "xxxx",
        "imgcred": "xxxx",
        "imgcredlink": "xxxx",
        "img": "Azure.png",
        "term": "Azure",
        "termdef": "The Azure cloud platform is more than 200 products and cloud services designed to help you bring new solutions to life—to solve today’s challenges and create the future. Build, run, and manage applications across multiple clouds, on-premises, and at the edge, with the tools and frameworks of your choice."
    }
    ,
    {
        "url": "https://tryhackme.com/room/xssgi",
        "title": "Cross-site Scripting (XSS)",
        "desc": "Learn how to detect and exploit XSS vulnerabilities, giving you control of other visitor's browsers.",
        "week": "06",
        "sort": "2022-05-26",
        "date": "26 May 2022",
        "accessed": "26 May 2022",
        "author": "Presented by Dax",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "2022-spring-06-ig-owasp-xss.png",
        "term": "XSS",
        "termdef": "Cross-Site Scripting (XSS) is a type of injection attack in which malicious scripts are injected into otherwise benign and trusted web pages. An attacker can exploit a vulnerability in an application to steal or modify legitimate data."
    }
    ,
    {
        "url": "https://www.base64decode.org/",
        "title": "Base64 Decoder",
        "desc": "Do you have to deal with Base64 format? Then this site is perfect for you! Use our super handy online tool to encode or decode your data.",
        "week": "06",
        "sort": "2022-05-26",
        "date": "26 May 2022",
        "accessed": "26 May 2022",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "https://www.base64-image.de/",
        "imgcred": "base64-image",
        "img": "base64.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://tryhackme.com/room/nmap01",
        "title": "TryHackMe | Nmap Live Host Discovery",
        "desc": "Learn how to use Nmap to discover live hosts using ARP scan, ICMP scan, and TCP/UDP ping scan.When we want to target a network, we want to find an efficient tool to help us handle repetitive tasks and answer the following questions: Which systems are up? What services are running on these systems?",
        "week": "05",
        "sort": "2022-05-09",
        "date": "09 May 2022",
        "accessed": "09 May 2022",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcred": "xxxx",
        "imgcredlink": "xxxx",
        "img": "a6b64823d42120e106cb7e89ceaa4817.png",
        "term": "ARP",
        "termdef": "Address Resolution Protocol is a communication protocol used for discovering the link layer address, such as a MAC address, associated with a given internet layer address, typically an IPv4 address."
    }
    ,
    {
        "url": "https://xsshunter.com/",
        "title": "What is XSS Hunter?",
        "desc": "XSS Hunter allows you to find all kinds of cross-site scripting vulnerabilities, including the often-missed blind XSS. The service works by hosting specialized XSS probes which, upon firing, scan the page and send information about the vulnerable page to the XSS Hunter service.",
        "week": "06",
        "sort": "2022-05-26",
        "date": "26 May 2022",
        "accessed": "26 May 2022",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "automatic_page_recon.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://tryhackme.com/room/owaspjuiceshop",
        "title": "OWASP Juice Shop",
        "desc": "This room uses the Juice Shop vulnerable web application to learn how to identify and exploit common web application vulnerabilities.",
        "week": "06",
        "sort": "2022-05-26",
        "date": "26 May 2022",
        "accessed": "26 May 2022",
        "author": "Cake",
        "authlink": "https://tryhackme.com/p/Cake",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "6gyZ7Vr.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://tryhackme.com/room/burpsuitebasics",
        "title": "Burp Suite: The Basics",
        "desc": "An introduction to using Burp Suite for Web Application pentesting",
        "week": "06",
        "sort": "2022-05-26",
        "date": "26 May 2022",
        "accessed": "11 May 2022",
        "author": "tryhackme",
        "authlink": "https://tryhackme.com/p/tryhackme",
        "author2": "MuirlandOracle",
        "authlink2": "https://tryhackme.com/p/MuirlandOracle",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "7e11c5dec4dba4336927aa7561e5c793.gif",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://tryhackme.com/room/burpsuiterepeater",
        "title": "Burp Suite: Repeater",
        "desc": "Learn how to use Repeater to duplicate requests in Burp Suite. Whilst we can craft requests by hand, it would be much more common to simply capture a request in the Proxy, then send that through to Repeater for editing/resending. With a request captured in the proxy, we can send to repeater either by right-clicking on the request and choosing 'Send to Repeater' or Ctrl + R. Switching back to Repeater, we can see that our request is now available.",
        "week": "xxxx",
        "sort": "2022-05-11",
        "date": "11 May 2022",
        "accessed": "11 May 2022",
        "author": "tryhackme",
        "authlink": "https://tryhackme.com/p/tryhackme",
        "author2": "MuirlandOracle",
        "authlink2": "https://tryhackme.com/p/MuirlandOracle",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "ae762b56b7ecb30a0d861221d41502f5.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://tryhackme.com/room/introtonetworking",
        "title": "Introductory Networking",
        "desc": "An introduction to networking theory and basic networking tools. The OSI (Open Systems Interconnection) Model is a standardised model which we use to demonstrate the theory behind computer networking. In practice, it's actually the more compact TCP/IP model that real-world networking is based off; however the OSI model, in many ways, is easier to get an initial understanding from.",
        "week": "xxxx",
        "sort": "2022-05-11",
        "date": "11 May 2022",
        "accessed": "11 May 2022",
        "author2": "MuirlandOracle",
        "authlink2": "https://tryhackme.com/p/MuirlandOracle",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "syn-acktra.jpeg",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://tryhackme.com/hacktivities",
        "title": "Learning paths for TryHackMe",
        "desc": "Learn how to pivot through a network by compromising a public facing web machine and tunnelling your traffic to access other machines in Wreath's network. (Streak limitation only for non-subscribed users)",
        "week": "01",
        "sort": "2022-05-11",
        "date": "11 May 2022",
        "accessed": "11 May 2022",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "introduction-to-cyber.jpg",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://tryhackme.com/path-action/beginner/join",
        "title": "Try Hack Me Complete Beginner Path",
        "desc": "This path will be looking at the following areas: Basic Linux - Get familiar with the linux command line, Web Application Security - Learn web application security concepts through the OWASP Top 10, Network Security - Using essential tools like NMAP to enumerate infrastructure, Scripting Challenges - Using Python and Bash to carry out different tasks, Privilege Escalation",
        "week": "xxxx",
        "sort": "2022-05-11",
        "date": "11 May 2022",
        "accessed": "xxxx",
        "author": "xxxx",
        "authlink": "https://tryhackme.com",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "deploy_access_hack_arrow.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://tryhackme.com/room/pythonbasics",
        "title": "Learn Python Basics for beginners in cybersecurity",
        "desc": "Using a web-based code editor, learn the basics of Python and put your knowledge into practice by eventually coding a short Bitcoin investment project.",
        "week": "06",
        "sort": "2022-05-20",
        "date": "20 May 2022",
        "accessed": "20 May 2022",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "24fbdd3df0afe5215613d6be2f328f45.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://tryhackme.com/room/pythonforcybersecurity",
        "title": "Python for Pentesters",
        "desc": "Python is probably the most widely used and most convenient scripting language in cybersecurity. This room covers real examples of Python scripts including hash cracking, key logging, enumeration and scanning.",
        "week": "06",
        "sort": "2022-05-23",
        "date": "23 May 2022",
        "accessed": "23 May 2022",
        "author": "tryhackme",
        "authlink": "https://tryhackme.com/p/tryhackme",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "dNJGqpN.png",
        "term": "New Programming Language!",
        "termdef": "This new <a class='ee' href='https://www.youtube.com/watch?v=5NORZrb2OHM'> programming language </a>is a  process oriented, dynamic, strong, esoteric programming language. All of the keywords/statements are from a song's lyrics."
    }
    ,
    {
        "url": "https://www.phishingbox.com/phishing-test",
        "title": "PhishingBox - Phishing Test",
        "desc": "Take this test to see if you can identify what is a real email or a phishing email. This is not an easy test. If you can continuously make an ‘A’ on this test, then you can effectively identify Phishing scams. PhishingBox’s built-in security awareness training will help you educate your employees by properly testing them with Phishing Quizzes and educational online courses to help combat the ongoing phishing threat.",
        "week": "07",
        "sort": "2022-06-01",
        "date": "01 June 2022",
        "accessed": "01 June 2022",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "phishing-test-q1.jpg",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://www.awseducate.com/student/s/",
        "title": "AWS Educate",
        "desc": "Your cloud journey starts here! No matter your goal, we’ve gathered the most useful content to build your cloud skills.",
        "week": "07",
        "sort": "2022-06-02",
        "date": "02 June 2022",
        "accessed": "02 June 2022",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "Lesson1 CO1.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://github.com/Ciphey/Ciphey",
        "title": "Decryption tool",
        "desc": "'i found a cool tool, it seems to work better than cyberchef magic :slightly_smiling_face: very neat. it decrypted Riley’s message in a pretty decent amount of time'",
        "week": "09",
        "sort": "2022-06-13",
        "date": "13 June 2022",
        "accessed": "13 June 2022",
        "author": "Shared by Sam",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "binoculars.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://www.cyberseek.org/",
        "title": "Cyber Seek: Hack the gap",
        "desc": "To help close the cybersecurity skills gap, CyberSeek provides detailed, actionable data about supply and demand in the cybersecurity job market. Students ask: Is there strong demand for cybersecurity jobs in my region? What skills and educational credentials do I need to enter a career in cybersecurity? How much can I make if I work in cybersecurity?",
        "week": "09",
        "sort": "2022-06-13",
        "date": "13 June 2022",
        "accessed": "13 June 2022",
        "author": "xxxx",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "tool_07.png",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://www.tripwire.com/state-of-security/security-data-protection/cyber-security/reexamining-laws-of-cybersecurity/",
        "title": "Reexamining the “5 Laws of Cybersecurity”",
        "desc": "xxxx",
        "week": "xxxx",
        "sort": "2022-06-19",
        "date": "19 June 2022",
        "accessed": "21 June 2022",
        "author": "TRIPWIRE GUEST AUTHORS",
        "authlink": "https://www.tripwire.com/state-of-security/contributors/tripwire-guest-authors/",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "5-Laws-of-Cybersecurity.jpg",
        "term": "Identity access management (IAM)",
        "termdef": "a framework of business processes, policies and technologies that facilitates the management of electronic or digital identities. With an IAM framework in place, information technology (IT) managers can control user access to critical information within their organizations. Systems used for IAM include single sign-on systems, two-factor authentication, multifactor authentication and privileged access management. These technologies also provide the ability to securely store identity and profile data as well as data governance functions to ensure that only data that is necessary and relevant is shared."
    }
    ,
    {
        "url": "https://tryhackme.com/room/metasploitintro",
        "title": "Metasploit: Introduction - An introduction to the main components of the Metasploit Framework",
        "desc": "An introduction to the main components of the Metasploit Framework.  The Metasploit Framework is a set of tools that allow information gathering, scanning, exploitation, exploit development, post-exploitation, and more. While the primary usage of the Metasploit Framework focuses on the penetration testing domain, it is also useful for vulnerability research and exploit development.",
        "week": "10",
        "sort": "2022-06-28",
        "date": "28 June 2022",
        "accessed": "28 June 2022",
        "author": "tryhackme",
        "authlink": "https://tryhackme.com/p/tryhackme",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "metasploit.png",
        "term": "Payloads",
        "termdef": "Scripts that will run on the target system."
    }
    ,
    {
        "url": "https://wazuh.com/blog/detecting-cobalt-strike-beacons-using-wazuh/",
        "title": "Detecting Cobalt Strike beacons using Wazuh",
        "desc": "Pipes are a section of memory used for interprocess communication. Pipes operate in a client-server model, the process that creates the pipe is the pipe server, and the process that connects to the pipe is the pipe client.",
        "week": "11",
        "sort": "2022-06-15",
        "date": "15 June 2022",
        "accessed": "29 June 2022",
        "author": "Chris Bassey",
        "authlink": "xxxx",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "01-3.png",
        "term": "Cobalt strike",
        "termdef": "A red team command and control framework used for adversary emulation. Due to its functionality and flexibility, it has been widely adopted by both red teams and threat actors. Multiple threat actors such as APT29, APT32, APT 41, APT19, UNC2452, FIN6 use cracked versions of Cobalt Strike in their attacks. Cobalt Strike payloads called beacons are implanted on compromised endpoints and are controlled from a C2 server. "
    }
    ,
    {
        "url": "https://hackaday.com/2022/06/18/notkia-building-an-open-and-linux-powered-numpad-phone/",
        "title": "NOTKIA: BUILDING AN OPEN AND LINUX-POWERED NUMPAD PHONE",
        "desc": "Many of us hackers have a longing for numpad-adorned mobile phones. We also have a shared understanding that, nowadays, such a phone has to be open and Linux-powered. Today’s project, Notkia, is the most promising and realistic effort at building a keypad phone that fits our requirements.",
        "week": "10",
        "sort": "2022-06-18",
        "date": "18 June 2022",
        "accessed": "25 June 2022",
        "author": "Arsenijs Picugins",
        "authlink": "https://hackaday.com/author/arsenijspicugins/",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "had_notkia_feat.webp",
        "term": "xxxx",
        "termdef": "xxxx"
    }
    ,
    {
        "url": "https://tryhackme.com/room/metasploitexploitation",
        "title": "Metasploit: Exploitation - Using Metasploit for scanning, vulnerability assessment and exploitation.",
        "desc": "Metasploit has a number of modules to scan open ports on the target system and network. You can list potential port scanning modules available using the search portscan command. The scanner/discovery/udp_sweep module will allow you to quickly identify services running over the UDP. This module will not conduct an extensive scan of all possible UDP services but does provide a quick way to identify services such as DNS or NetBIOS.",
        "week": "xxxx",
        "sort": "2022-06-01",
        "date": "01 June 2022",
        "accessed": "01 June 2022",
        "author": "tryhackme",
        "authlink": "https://tryhackme.com/p/tryhackme",
        "imgcredlink": "xxxx",
        "imgcred": "xxxx",
        "img": "metasploit.png",
        "term": "UDP  (User Datagram Protocol)",
        "termdef": "A communication protocol used across the Internet for especially time-sensitive transmissions such as video playback or DNS lookups. It speeds up communications by not formally establishing a connection before data is transferred. This allows data to be transferred very quickly, but it can also cause packets to become lost in transit — and create opportunities for exploitation in the form of DDoS attacks."
    }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
    // ,
    // {
    //     "url": "xxxx",
    //     "title": "xxxx",
    //     "desc": "xxxx",
    //     "week": "xxxx",
    //     "sort": "2022-06-01",
    //     "date": "01 June 2022",
    //     "accessed": "01 June 2022",
    //     "author": "xxxx",
    //     "authlink": "xxxx",
    //     "imgcredlink": "xxxx",
    //     "imgcred": "xxxx",
    //     "img": "xxxx",
        // "term": "xxxx",
        // "termdef": "xxxx"
    // }
];